### ISSUE TITLE
Why new repo?

### ISSUE THREAD

**Issue by bruvv** [fredrikbaberg/ha-3dprinter-addons#50]
Good to see you back! I was wondering. Why a new repo and not update the current one?

**Comment by fredrikbaberg** [comment]
I had to focus on studies but am finally done so I hope to have some more time now.

The idea of a new repo is to make a clean start and only focus on add-ons related to 3D-printing. It would also be a way to clean out the older, deprecated versions of the add-on that are kept for legacy reasons - I don't know if someone is using them, and therefore I didn't want to completely remove them.

Is there a strong reason to stay with the old repository? If so I could re-evaluate the decision.

**Comment by bruvv** [comment]
No no complaints or reasons! Happy to see you are back. I was about to pickup the 3d printer again too :) thanks for explaining, I have added it to home assistant and switched the addon!
