### ISSUE TITLE
Socat

### ISSUE THREAD

**Issue by timotoots** [fredrikbaberg/ha-3dprinter-addons#51]
### If this relates to an existing add-on, please select which one.

3DPrinter-OctoPrint

### What feature would you like to be added?

Problem is that Home Assistant computer might not be near the 3D printer. There is a Wifi2Serial firmware for ESP32 that could forward messages to 3D printer from Octoprint. Like:
https://github.com/luc-github/ESP3D/

Running add-on on Home Assisant OS does not let you use socat to create virtual UART. Would be great if this add-on would use something like this to create a virtual UART port to network:
https://github.com/jakekeeys/octoprint-socat

Thanks for the initiative! I think running Octoprint on HA is a good idea, do not need another Raspberry running!

**Comment by timotoots** [comment]
I actually got this working with a plugin:
https://github.com/hellerbarde/OctoPrint-Network-Printing

I tried ESP3D, but with no luck. It should also work with it. Then I tried with ESPHome UART plugin:
https://github.com/tube0013/esphome-stream-server-v2

It actually worked and I was already very surprised. But the printing speed was much slower than directly from SD card. And it dropped connection as well sometimes. So not so reliable, but I do not know which part was letting me down. One idea would be trying with a ESP32 board with ethernet. It would be great solution to host Octoprint in HA and ESP boards on the printers.

**Comment by fredrikbaberg** [comment]
Thank you, that should help. I've setup the plugin for testing.
I started to look at it yesterday, just to get started with socat, and now looked at the OctoPrint-Network-Printing plugin.

Looking at this again, I'm not sure what adding socat to the add-on would bring that the plugin doesn't already do?

If I got it right, the idea can be described by the following flowchart:

```mermaid
graph LR;
  VM[Home Assistant with add-on 3DPrinter-OctoPrint] <-- Network ---> ESP3D[3D Printer];
```

In my case I have two instances of Home Assistant OS, one in a VM and one on a Raspberry Pi 3B+ (connected to 3D printer). To mimic ESP3D I've added ser2net to the Raspberry Pi (separate add-on, may publish it next week but it's simple). With that I could use [OctoPrint-Network-Printing](https://github.com/hellerbarde/OctoPrint-Network-Printing) according to the instructions and get temperature readings (haven't tried to print, may try that next week).

**Comment by fredrikbaberg** [comment]
A minor update on this, I'm currently printing using the setup described above (just a plugin and an add-on with ser2net). For now it's a temperature tower printing, as I anyways need to tune the printer. PID auto-tune also worked from OctoPrint.

@timotoots before I close this, am I missing something here? Is socat still needed?

**Comment by timotoots** [comment]
I have not tried the it more, but I guess it's not needed. Thanks for the trouble!

**Comment by fredrikbaberg** [comment]
Then I'll close this for now. Please let me know if you find a new need for this.
