### ISSUE TITLE
No Stream, Static Image works fine

### ISSUE THREAD

**Issue by NAM1025** [fredrikbaberg/ha-3dprinter-addons#55]
### Describe the issue you are experiencing

Accessing the UI for mjpg-streamer through Home Assistant, I can see the still images under the "Static" page, but the "Stream" page shows a broken image icon. 

Edit:
Javascript sample works fine as well. I can see the video playing there. Just doesn't work on the "Stream" page.

### Which add-on are you reporting an issue with?

Camera-mjpg-streamer

### What is the version of the add-on?

2022.7.0

### Steps to reproduce the issue

1. Installed Camera-mjpg-streamer
2. Started the addon
3. Open Web UI
4. Click "Stream" in navigation

![image](https://user-images.githubusercontent.com/28747418/215867405-5c7db1d9-3974-4eb2-b368-57511ee46575.png)

### Additional information

If I go to the url on the VideoLAN page in the browser it shows me
![image](https://user-images.githubusercontent.com/28747418/215867810-1de2791e-b793-481a-8fff-47b31a62e1eb.png)

**Comment by NAM1025** [comment]
Okay, figured it out. I didn't realize there was a disabled section of the mjpg-streamer configuration (about what port to use). I set the port, and instead of using the URL from the mjpg-streamer page, I went to <home-assistant-url>:port/?action=stream and now I can see the stream.

**Comment by fredrikbaberg** [comment]
Hi,
Thank you for the bug report. I'm aware of this, but do not currently plan to fix it (as I'm not sure how to do so). For me the main reason for Ingress support for this add-on has been for debugging.

As you wrote, you can specify a port for external access. It should also be possible to use it as a [mjpg IP camera](https://www.home-assistant.io/integrations/mjpeg/) in Home Assistant using the internal hostname (e.g. `http://b7aa59c4-camera-mjpg-streamer:80/?action=stream`).
