### ISSUE TITLE
HA config directory isn't mapped

### ISSUE THREAD

**Issue by pelrun** [fredrikbaberg/ha-3dprinter-addons#81]
### Describe the issue you are experiencing

Config.yaml doesn't currently have the map: section that tells HA to mount the global config directory into the addon container. This means the octoprint configuration is trapped inside it's own copy of the config directory that is not accessible by HA and can't therefore be edited or backed up except via Octoprint's UI.

Should be including "config:rw" at an absolute minimum, and probably some of the others as well.

### Which add-on are you reporting an issue with?

3DPrinter-OctoPrint

### What is the version of the add-on?

2023.03.1

**Comment by fredrikbaberg** [comment]
Thank you for your feedback!

This is intended behaviour, for a few reasons:
* Security. Mapping `/config` would mean OctoPrint has access to the full `/config` folder. If I recall correctly it is not possible to limit access to a single subfolder, this means the addon can access Home Assistant configuration and the other way around.
* Backups. Backup and restore of Home Assistant and the addon can be done independently. **Note:** _You can backup the addon from Home Assistant, not only from within OctoPrint._
* Ease of development. Multiple versions can be installed and run simultaneously.

I am aware that this makes it more difficult to modify OctoPrint configuration files manually, but haven't seen much need to do so outside of development.

**Comment by pelrun** [comment]
Well, then my issue should probably be that HA *isn't* successfully backing up Octoprint, for this reason or another. And it's definitely on the backup side, because the tarballs I'm generating contain all my addons except for OP.

**Comment by pelrun** [comment]
Edit: never mind, I've just generated a new backup to doublecheck and *this* time it's grabbed the addon. Not sure why it failed all the previous times, but if it pops up again I'll reopen.

**Comment by HydrelioxGitHub** [comment]
I've not understand all of your discussion but it seems that is related with my question. Where Octoprint store my gcode files ? All other addon I've installed have a folder where files are stored ( in the addon_configs share).

**Comment by fredrikbaberg** [comment]
> I've not understand all of your discussion but it seems that is related with my question. Where Octoprint store my gcode files ? All other addon I've installed have a folder where files are stored ( in the addon_configs share).

All files are stored in an internal folder, not publicly available to users. When I first created this version of the addon the `addon_configs` share wasn't available. Had it been, I would probably have used it. Changing the folder now would require scripts for migration and modifying OctoPrint configuration, something I would prefer not to do.

**Comment by HydrelioxGitHub** [comment]
Could the migration be done using Octoprint backup feature ? I mean 
- Create a backup in Octoprint 
- Update the add-on with the new folder mapping
- Restore backup

Maybe I miss something as I don't know if there are some files of the add-on are out of the scope of the Octoprint backup.

Or maybe create a separated add-on repo with the different folder mapping.

I'm a newbie here so these suggestions can be silly and I don't know how much work that has to be done to achieve anything. 

Anyway, thank for your work on this add-on.
