### ISSUE TITLE
Upload Size Limit

### ISSUE THREAD

**Issue by jneilliii** [fredrikbaberg/ha-3dprinter-addons#88]
### Describe the issue you are experiencing

User reported issue uploading large files to OctoPrint instance created by this add-on.

### Which add-on are you reporting an issue with?

3DPrinter-OctoPrint

### What is the version of the add-on?

unsure

### Steps to reproduce the issue

Try to upload a very large gcode file. 

### Additional information

I suspect that the client_max_body_size of nginx reverse proxy needs to be adjusted. The example configs on the OctoPrint forum for nginx sets this as 0 for unlimited restrictions.

**Comment by fredrikbaberg** [comment]
Thank you, I'll look into it. I'm not using nginx here, but I'll look for a similar setting.

For recreating, do you know how large a "very large gcode file" would be?
Also, any suggestions how to generate such a file, other than adding a lot of random data to it?

**Comment by jneilliii** [comment]
I've seen a couple of other random posts about HA and 16MB limits, so not sure what the actual threshold is, but here are a couple of files the user provided in Discord as failing to be uploaded.

[large_gcode.zip](https://github.com/fredrikbaberg/ha-3dprinter-addons/files/13932790/large_gcode.zip)

**Comment by fredrikbaberg** [comment]
I am unable to recreate this with the current version of the add-on (2023.03.1), that includes uploading a file of 995MB.
_It caused stability issues on my Raspberry Pi 3, so I do not recommend uploading such a large file, but it did not seem related to reverse proxy configuration. I have the same version on my PC where it worked fine._

I'll need some more information to try to resolve this, such as hardware and the version of the add-on. Will get on Discord to see if we can figure it out there.

**Comment by fredrikbaberg** [comment]
I will close this issue as it occurs on another add-on in another repository, it is not something I will be able to solve.

That add-on should have been deprecated, but I've now updated the description to make it more clear and will see if I can have it completely removed.
