### ISSUE TITLE
Possibly outdated documentation for getting addon host

### ISSUE THREAD

**Issue by jtulak** [fredrikbaberg/ha-3dprinter-addons#90]
### Describe the issue you are experiencing

The link to Addon Settings in the section "Accessing camera from Home Assistant" in the documentation of mjpg plugin is probably outdated. I have the latest version of HA OS installed just today, and when I click on the link, it shows "plugin not found" error. I have supervised installation, but I'm also new to HA, so I might be doing something wrong.

Also the example urls in the section can be actually hardcoded to `cce6f2d5_camera-mjpg-streamer` as long as this repository is not moved/renamed, because the hash is actually the first few characters of sha1(<github url>).

```
MJPEG URL: http://cce6f2d5_camera-mjpg-streamer/?action=stream
Still image URL: http://cce6f2d5_camera-mjpg-streamer/?action=snapshot
```

HA info:
Core 2024.1.3
Supervisor 2023.12.0
Operating System 11.4
Frontend 20240104.0

### Which add-on are you reporting an issue with?

Camera-mjpg-streamer

### What is the version of the add-on?

2022.7.0

### Steps to reproduce the issue

1. Open the mjpg plugin, go to Documentation tab
2. Try to find out what url to use to see the pictures
3. Lose your head because the link doesn't works. :)

**Comment by jtulak** [comment]
Also, I couldn't get the stream working in any way, just snapshot is working, but that's expected from what I understand about ingress limitation for this plugin. And the javascript solution is usable. So maybe the stream url should not be shown at all.

**Comment by fredrikbaberg** [comment]
The stream is an issue as it needs to be available for the client accessing it, not just the OctoPrint instance, so using the internal hostname (e.g. `cce6f2d5_camera-mjpg-streamer`) isn't possible. I'm not sure how to solve that in a secure way, as there is no [access control from OctoPrint for camera stream](https://community.octoprint.org/t/why-is-there-no-access-control-for-the-webcam-in-octoprint-why-is-my-webcam-always-on/233).

My camera is currently not in use, but I believe my previous setup was to have a reverse proxy setup for the camera stream.

I'll go through the documentation when I'm updating the add-ons and see if I can change the formulation to make things more clear.

**Comment by fredrikbaberg** [comment]
Reading this again I realise it's not related to 3DPrinter-OctoPrint, sorry about that.

I'm still going through the documentation.
