### ISSUE TITLE
Home assistant addon doesnt work

### ISSUE THREAD

**Issue by chechilll** [fredrikbaberg/ha-3dprinter-addons#99]
### Describe the issue you are experiencing

Can't run the addon

### Which add-on are you reporting an issue with?

3DPrinter-OctoPrint

### What is the version of the add-on?

2024.01.2

### Steps to reproduce the issue

1. Instaled addon 2024.01.2
2. Run the Addon

### Anything in the add-on logs that might be useful?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/octoprint.sh
/etc/cont-init.d/octoprint.sh: line 9: octoprint: command not found
Python 3.9.2
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e1cd430>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/octoprint/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e1cd220>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/octoprint/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e1cd070>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/octoprint/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e1cd940>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/octoprint/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e1cdbb0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/octoprint/
ERROR: Could not find a version that satisfies the requirement octoprint==1.9.3
ERROR: No matching distribution found for octoprint==1.9.3
cont-init: info: /etc/cont-init.d/octoprint.sh exited 1
cont-init: info: running /etc/cont-init.d/proxy.sh
curl: (7) Couldn't connect to server
[19:48:07] ERROR: Something went wrong contacting the API
curl: (7) Couldn't connect to server
[19:48:07] ERROR: Something went wrong contacting the API
cont-init: info: /etc/cont-init.d/proxy.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by fredrikbaberg** [comment]
This looks like a network issue, not the add-on itself. I did a reinstall on my generic x86-64 install without encountering the same issue.

Could you try to stop and start the add-on again, and see if you get the same issue?

**Comment by chechilll** [comment]
Its not a network issue. I run it on a raspberry pi 4 (8gb ram) with other 6 addons without problems.
I tried reinstall, start/stop, reload, reboot with same result. Installing octoprint with docker works but makes home Assistant not compliance.

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fredrikbaberg** [comment]
I'm currently unable to recreate the issue. I'll see if I get some time to look at it during the weekend.

A quick search indicates the issue could be related to proxy configuration (https://stackoverflow.com/questions/52815784/python-pip-raising-newconnectionerror-while-installing-libraries). Did you also try to reboot the Raspberry Pi 4 itself?

**Comment by chechilll** [comment]
Did you also try to reboot the Raspberry Pi 4 itself? Yes, as i said I tried reinstall, start/stop (addon), reload (addon), reboot (Raspberry) with same result

**Comment by zagi988** [comment]
I have the same problem, running on a Debian server with HA Supervised.

**Comment by zagi988** [comment]
Any update on this?

**Comment by fredrikbaberg** [comment]
No update yet, I haven't been able to replicate the issue (and haven't had time to look properly at it).
I'll have to prepare a HA Supervised setup to see if I can figure out why it doesn't work.

**Comment by fredrikbaberg** [comment]
I've now been able to replicate the issue, will look at it during the weekend.

**Comment by chechilll** [comment]
Thanks, ...waiting the patch :)

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chechilll** [comment]
It still docent work

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chechilll** [comment]
It still doesnt work

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chechilll** [comment]
It still doesnt work

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chechilll** [comment]
It still doent work, no info from developer. Still in version 2024.01.2

**Comment by fredrikbaberg** [comment]
I've been out of resources, mostly time, to work on this.

Pull requests are most welcome.

**Comment by fredrikbaberg** [comment]
Finally identified the issue to be in the AppArmor profile. Not sure why it only occurs on HA Supervised, it should break all installs.
No update published yet.
